Given the data is recorded by research staff. We wanted to engineer some the metrics to our model's convinience. 

Convertions:
for a course of 36 months, food consumption records at 

*   0/never == 0
*   1/once a month == 36,
*   2/once a fortnight == 72
*   3/once a week == 144
*   4/2-3 times per week == 422
*   5/4-6 times per week == 720
*   6/Daily == 1080
*   7/more than once daily == 2160.

In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
food_allergens = pd.read_excel('full_data.xlsx')

In [ ]:
food_allergens.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 74 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   Participant ID                                                                 1303 non-null   int64
 1   ethnicity                                                                      1303 non-null   int64
 2   asthma_family_history                                                          1301 non-null   float64
 3   mother_has_asthma                                                              1301 non-null   float64
 4   father has asthma                                                              1301 non-null   float64
 5   family history of eczema                                                       1301 non-null   float64
 6   mother has eczema                                                              1301 non-null   float64
 7   father has eczema                                                              1301 non-null   float64
 8   family history of hayfever                                                     1301 non-null   float64
 9   mother has hayfever                                                            1301 non-null   float64
 10  father has hayfever                                                            1301 non-null   float64
 11  family history of food allergy                                                 1301 non-null   float64
 12  mother has food allergy                                                        1301 non-null   float64
 13  father has food allergy                                                        1301 non-null   float64
 14  mother smoked during pregnancy                                                 1301 non-null   float64
 15  any pets owned at enrolment                                                    1301 non-null   float64
 16  Parent reports child had eczema before enrolment (parent and/or Dr diagnosed)  1225 non-null   float64
 17  freq of milk baby food consumed at 36 months                                   1225 non-null   float64
 18  freq of wheat baby food consumed at 36 months                                  1225 non-null   float64
 19  freq of egg baby food consumed at 36 months                                    1225 non-null   float64
 20  freq of cereal consumed at 36 months                                           1225 non-null   float64
 21  freq of bread consumed at 36 months                                            1225 non-null   float64
 22  freq of dried pasta consumed at 36 months                                      1225 non-null   float64
 23  freq of fresh pasta consumed at 36 months                                      1225 non-null   float64
 24  freq of pastry consumed at 36 months                                           1225 non-null   float64
 25  freq of tortilla consumed at 36 months                                         1225 non-null   float64
 26  freq of egg consumed at 36 months                                              1225 non-null   float64
 27  freq of croissant consumed at 36 months                                        1225 non-null   float64
 28  freq of scone consumed at 36 months                                            1225 non-null   float64
 29  freq of cake consumed at 36 months                                             1225 non-null   float64
 30  freq of pancake consumed at 36 months                                          1225 non-null   float64
 31  freq of jaffa consumed at 36 months                                            1225 non-null   float64
 32  freq of quiche consumed at 36 months                                           1225 non-null   float64
 33  freq of mayo consumed at 36 months                                             1225 non-null   float64
 34  freq of yoghurt consumed at 36 months                                          1225 non-null   float64
 35  freq of custard consumed at 36 months                                          1225 non-null   float64
 36  freq of cream consumed at 36 months                                            1225 non-null   float64
 37  freq of soft cheese consumed at 36 months                                      1225 non-null   float64
 38  freq of cheese sauce consumed at 36 months                                     1225 non-null   float64
 39  freq of hard cheese consumed at 36 months                                      1225 non-null   float64
 40  freq of fish fingers consumed at 36 months                                     1225 non-null   float64
 41  freq of fish cakes consumed at 36 months                                       1225 non-null   float64
 42  freq of fish pie consumed at 36 months                                         1225 non-null   float64
 43  freq of fish baby food consumed at 36 months                                   1225 non-null   float64
 44  freq of peanut butter consumed at 36 months                                    1225 non-null   float64
 45  freq of peanut cereal consumed at 36 months                                    1225 non-null   float64
 46  freq of peanut choc consumed at 36 months                                      1225 non-null   float64
 47  freq of hummus consumed at 36 months                                           1225 non-null   float64
 48  freq of tahini consumed at 36 months                                           1225 non-null   float64
 49  freq of sesame crackers consumed at 36 months                                  1225 non-null   float64
 50  freq of sesame snaps consumed at 36 months                                     1225 non-null   float64
 51  freq of sesame bread consumed at 36 months                                     1225 non-null   float64
 52  admission to A&E since 33 month questionnaire                                  107 non-null    float64
 53  birth weight kg                                                                1302 non-null   float64
 54  Child's sex                                                                    1303 non-null   int64
 55  skin prick test to wheat at 36 month clinic visit                              1184 non-null   float64
 56  skin prick test to sesame at 36 month clinic visit                             1182 non-null   float64
 57  skin prick test to peanut at 36 month clinic visit                             1184 non-null   float64
 58  skin prick test to milk at 36 month clinic visit                               1183 non-null   float64
 59  skin prick test to cod at 36 month clinic visit                                1182 non-null   float64
 60  skin prick test to egg at 36 month clinic visit                                1183 non-null   float64
 61  skin prick test to kiwi at 36 month clinic visit                               1179 non-null   float64
 62  skin prick test to raw egg at 36 month clinic visit                            1181 non-null   float64
 63  skin prick test to soya at 36 month clinic visit                               1180 non-null   float64
 64  skin prick test to cat at 36 month clinic visit                                1140 non-null   float64
 65  skin prick test to dog at 36 month clinic visit                                1141 non-null   float64
 66  skin prick test to house dust mite at 36 month clinic visit                    1142 non-null   float64
 67  skin prick test to grass pollen at 36 month clinic visit                       1146 non-null   float64
 68  skin prick test to tree pollen at 36 month clinic visit                        1145 non-null   float64
 69  skin prick test to Brazil nut at 36 month clinic visit                         1144 non-null   float64
 70  skin prick test to hazelnut at 36 month clinic visit                           1143 non-null   float64
 71  skin prick test to cashew at 36 month clinic visit                             1142 non-null   float64
 72  skin prick test to almond at 36 month clinic visit                             1139 non-null   float64
 73  skin prick test to walnut at 36 month clinic visit                             1140 non-null   float64
dtypes: float64(71), int64(3)
memory usage: 753.4 KB

In [ ]:
# create a list of our conditions
conditions = [
    (food_allergens['4months_milk_consumption'] == 0),
    (food_allergens['4months_milk_consumption'] == 1),
    (food_allergens['4months_milk_consumption'] == 2),
    (food_allergens['4months_milk_consumption'] == 3),
    (food_allergens['4months_milk_consumption'] == 4),
    (food_allergens['4months_milk_consumption'] == 5),
    (food_allergens['4months_milk_consumption'] == 6),
    (food_allergens['4months_milk_consumption'] == 7)
    ]

# create a list of the values we want to assign for each condition
values = [0, 4, 8, 12, 32, 64, 122, 183]

# create a new column and use np.select to assign values to it using our lists as arguments
food_allergens['milk_baby_food'] = np.select(conditions, values)

# display updated DataFrame
food_allergens.head()

   ParticipantId  ethnicity  ...  aeadmit_q4m  milk_baby_food
0              1          0  ...          0.0               0
1              2          0  ...          0.0               0
2              3          0  ...          0.0               0
3              4          3  ...          NaN               0
4              5          0  ...          0.0              32

[5 rows x 58 columns]

In [ ]:
lst = ['freq of milk baby food consumed at 36 months',
'freq of wheat baby food consumed at 36 months','freq of egg baby food consumed at 36 months',
'freq of cereal consumed at 36 months','freq of bread consumed at 36 months',
'freq of dried pasta consumed at 36 months','freq of fresh pasta consumed at 36 months',
'freq of pastry consumed at 36 months','freq of tortilla consumed at 36 months','freq of egg consumed at 36 months',
'freq of croissant consumed at 36 months','freq of scone consumed at 36 months','freq of cake consumed at 36 months',
'freq of pancake consumed at 36 months','freq of jaffa consumed at 36 months','freq of quiche consumed at 36 months',
'freq of mayo consumed at 36 months','freq of yoghurt consumed at 36 months','freq of custard consumed at 36 months',
'freq of cream consumed at 36 months','freq of soft cheese consumed at 36 months',
'freq of cheese sauce consumed at 36 months','freq of hard cheese consumed at 36 months',
'freq of fish fingers consumed at 36 months','freq of fish cakes consumed at 36 months',
'freq of fish pie consumed at 36 months','freq of fish baby food consumed at 36 months',
'freq of peanut butter consumed at 36 months','freq of peanut cereal consumed at 36 months',
'freq of peanut choc consumed at 36 months','freq of hummus consumed at 36 months',
'freq of tahini consumed at 36 months','freq of sesame crackers consumed at 36 months',
'freq of sesame snaps consumed at 36 months','freq of sesame bread consumed at 36 months']


for i in lst:
  conditions = [
    (food_allergens[i] == 0),
    (food_allergens[i] == 1),
    (food_allergens[i] == 2),
    (food_allergens[i] == 3),
    (food_allergens[i] == 4),
    (food_allergens[i] == 5),
    (food_allergens[i] == 6),
    (food_allergens[i] == 7)
    ]

  # create a list of the values we want to assign for each condition
  values = [0, 36, 72, 144, 422, 720, 1080, 2160]
  food_allergens[i+'_new']  = np.select(conditions, values)

In [ ]:
food_allergens.shape

(1303, 109)

In [ ]:
food_allergens.to_csv('added_food_allergens.csv')